#!/bin/bash
VIRTENV_HOME=$OPENSHIFT_DEPENDENCIES_DIR/virtualenv/

echo "Installing dependencies..."

# create virtualenv
if [ ! -d $VIRTENV_HOME ]; then
    # Create virtualenv and install necessary packages
    virtualenv --no-site-packages $VIRTENV_HOME
fi

# activate virtualenv
source $VIRTENV_HOME/bin/activate

#install dependencies
pip uninstall shalk --no-cache-dir --yes
pip install --no-cache-dir $OPENSHIFT_REPO_DIR/

#import the ngrams db files
if [ ! -d $OPENSHIFT_DATA_DIR/ngrams ]; then
    mkdir -p $OPENSHIFT_DATA_DIR/ngrams
    cp $OPENSHIFT_REPO_DIR/data/* $OPENSHIFT_DATA_DIR/ngrams/
fi

# install nltk files
if [ ! -d $OPENSHIFT_DATA_DIR/nltk ]; then
    echo "Downloading NLTK corpora..."
    mkdir -p $OPENSHIFT_DATA_DIR/nltk
    python -m nltk.downloader cmudict punkt maxent_treebank_pos_tagger universal_tagset -d $OPENSHIFT_DATA_DIR/nltk
fi

deactivate
echo "Build finished!"
