#!/bin/bash
VIRTENV_HOME=$OPENSHIFT_DEPENDENCIES_DIR/virtualenv/

echo "Installing dependencies..."

# Delete previously built virtualenv
if [ -d $VIRTENV_HOME ]; then
    rm -rf $VIRTENV_HOME
fi

# Create virtualenv and install necessary packages
virtualenv --no-site-packages $VIRTENV_HOME
source $VIRTENV_HOME/bin/activate

#install dependencies
pip install $OPENSHIFT_REPO_DIR/

#import the ngrams db files
if [ ! -d $OPENSHIFT_DATA_DIR/ngrams ]; then
    mkdir -p $OPENSHIFT_DATA_DIR/ngrams
    cp $OPENSHIFT_REPO_DIR/data/* $OPENSHIFT_DATA_DIR/ngrams/
fi

if [ ! -d $OPENSHIFT_DATA_DIR/nltk ]; then
    echo "Downloading NLTK corpora..."
    mkdir -p $OPENSHIFT_DATA_DIR/nltk
    exec `python -m nltk.downloader brown -d $OPENSHIFT_DATA_DIR/nltk`
fi

deactivate
echo "Build finished!"
