#!/bin/bash
VIRTENV_HOME=$OPENSHIFT_DEPENDENCIES_DIR/virtualenv/
echo "Running app..."
source $VIRTENV_HOME/bin/activate
nohup webapp --host=${OPENSHIFT_DIY_IP} --port=${OPENSHIFT_DIY_PORT} --mongodb_url=${OPENSHIFT_MONGODB_DB_URL} > ${OPENSHIFT_DIY_LOG_DIR}/shalk.log 2>&1 &
